# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: greet.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import greet_pb2 as greet__pb2


class GreetService(Protocol):
    async def greet(self, request: greet__pb2.GreetRequest, ctx: RequestContext) -> greet__pb2.GreetResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class GreetServiceASGIApplication(ConnectASGIApplication[GreetService]):
    def __init__(self, service: GreetService | AsyncGenerator[GreetService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/greet.v1.GreetService/Greet": Endpoint.unary(
                    method=MethodInfo(
                        name="Greet",
                        service_name="greet.v1.GreetService",
                        input=greet__pb2.GreetRequest,
                        output=greet__pb2.GreetResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.greet,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/greet.v1.GreetService"


class GreetServiceClient(ConnectClient):
    async def greet(
        self,
        request: greet__pb2.GreetRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> greet__pb2.GreetResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Greet",
                service_name="greet.v1.GreetService",
                input=greet__pb2.GreetRequest,
                output=greet__pb2.GreetResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class GreetServiceSync(Protocol):
    def greet(self, request: greet__pb2.GreetRequest, ctx: RequestContext) -> greet__pb2.GreetResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class GreetServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: GreetServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            endpoints={
                "/greet.v1.GreetService/Greet": EndpointSync.unary(
                    method=MethodInfo(
                        name="Greet",
                        service_name="greet.v1.GreetService",
                        input=greet__pb2.GreetRequest,
                        output=greet__pb2.GreetResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.greet,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/greet.v1.GreetService"


class GreetServiceClientSync(ConnectClientSync):
    def greet(
        self,
        request: greet__pb2.GreetRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> greet__pb2.GreetResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Greet",
                service_name="greet.v1.GreetService",
                input=greet__pb2.GreetRequest,
                output=greet__pb2.GreetResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
